# Generated by Django 5.1.1 on 2024-09-28 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('assistance_id', models.AutoField(primary_key=True, serialize=False)),
                ('assistance_first_name', models.CharField(max_length=50)),
                ('assistance_middle_name', models.CharField(max_length=50)),
                ('assistance_last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('type_of_assistance', models.CharField(choices=[('Death', 'Death'), ('Hospitalization', 'Hospitalization')], max_length=50)),
                ('assistance_status', models.BooleanField(default=False)),
                ('assistance_evidence_first', models.FileField(upload_to='assistance/proof/')),
                ('assistance_evidence_second', models.FileField(upload_to='assistance/proof/')),
            ],
            options={
                'verbose_name': 'Assistance',
                'verbose_name_plural': 'Assistances',
                'db_table': 'assistance',
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('beneficiary_id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_first_name', models.CharField(max_length=50)),
                ('beneficiary_middle_name', models.CharField(blank=True, max_length=50)),
                ('beneficiary_last_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('relationship', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Child', 'Child'), ('Spouse', 'Spouse')], max_length=50)),
                ('date_of_birth', models.DateField()),
                ('proof', models.FileField(upload_to='beneficiary/proof/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benefeciary',
                'verbose_name_plural': 'Beneficiaries',
                'db_table': 'benefeciary',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('place_of_birth', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('employee_id', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('Teacher 1', 'Teacher 1'), ('Teacher 2', 'Teacher 2'), ('Teacher 3', 'Teacher 3'), ('Teacher 4', 'Teacher 4'), ('Teacher 5', 'Teacher 5'), ('Principal', 'Principal'), ('ADAS', 'ADAS')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('school_affiliation', models.CharField(max_length=100)),
                ('membership_status', models.BooleanField(default=False)),
                ('beneficiary', models.ManyToManyField(to='system.beneficiary')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Membership',
                'db_table': 'membership',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('payment_type', models.CharField(choices=[('Membership', 'Membership Fee'), ('Delegation Pay', 'Delegation Pay'), ('Trust Fund', 'Trust Fund'), ('Visitors Fund', 'Visitors Fund')], max_length=50)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
            },
        ),
    ]
