# Generated by Django 5.1.1 on 2024-12-01 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Amount of Expenses')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
            },
        ),
        migrations.AlterField(
            model_name='assistance',
            name='assistance_evidence_second',
            field=models.ImageField(help_text='Upload hospital certificate', upload_to='assistance/proof/'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='school_affiliation',
            field=models.CharField(choices=[('Dapiawan CES', 'Dapiowan CES'), ('Datu Pendililang ES', 'Datu Pendililang ES'), ('Madia IS', 'Madia IS'), ('Elian ES', 'Elian ES'), ('Gawang ES', 'Gawang ES'), ('Kitango ES', 'Kitango ES'), ('Kitapok ES', 'Kitapok ES'), ('Datu Kogia ES', 'Datu Kogia ES'), ('Dimaukom Utto ES', 'Dimaukom Utto ES'), ('Dimaukom ES', 'Dimaukom ES')], help_text='School affiliation of the employee', max_length=100),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user_id',
            field=models.ForeignKey(help_text='Employee who want to be a member', limit_choices_to={'user_type': 'Employee'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
