# Generated by Django 5.1.1 on 2024-12-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_schoolyear_primary_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='primary_school_year',
            field=models.BooleanField(default=False, help_text='Toggle for primary school years'),
        ),
        migrations.AddConstraint(
            model_name='schoolyear',
            constraint=models.UniqueConstraint(condition=models.Q(('primary_school_year', True)), fields=('primary_school_year',), name='unique_primary_school_year'),
        ),
    ]
