# Generated by Django 5.1.1 on 2024-12-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_schoolyear_unique_primary_school_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependents',
            options={'verbose_name': 'Dependent', 'verbose_name_plural': 'Dependents'},
        ),
        migrations.AlterModelOptions(
            name='ledger',
            options={'verbose_name': 'Ledger', 'verbose_name_plural': 'Ledgers'},
        ),
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'verbose_name': 'School year', 'verbose_name_plural': 'School years'},
        ),
        migrations.RemoveConstraint(
            model_name='schoolyear',
            name='unique_primary_school_year',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='recorded_by',
        ),
        migrations.AlterField(
            model_name='assistance',
            name='amount_released',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount to be released by the assistance', max_digits=10),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='primary_school_year',
            field=models.BooleanField(default=False, help_text='Toggle if primary school year'),
        ),
        migrations.AddConstraint(
            model_name='schoolyear',
            constraint=models.UniqueConstraint(condition=models.Q(('primary_school_year', True)), fields=('primary_school_year',), name='unique_primary_school_year', violation_error_message='Only one school year should be specified as primary school year, please try again.'),
        ),
    ]
