# Generated by Django 5.1.1 on 2024-09-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_rename_assistance_id_assistance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='amount_released',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
