# Generated by Django 5.1.1 on 2024-09-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_assistance_amount_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
