# Generated by Django 5.1.1 on 2024-12-01 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_remove_membership_beneficiary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='death_cert',
            field=models.ImageField(blank=True, help_text='Upload death certificate', null=True, upload_to='assistance/proof/'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='beneficiary',
            field=models.OneToOneField(blank=True, help_text='Select beneficiary of the employee, select only one.', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.beneficiary'),
        ),
    ]
