# Generated by Django 5.1.1 on 2024-12-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_assistance_amount_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='contact_number',
            field=models.CharField(help_text='Contact number of the employee', max_length=11),
        ),
        migrations.AlterField(
            model_name='membership',
            name='employee_id',
            field=models.CharField(help_text='Employee ID of the employee', max_length=50, unique=True),
        ),
    ]
