# Generated by Django 5.1.1 on 2024-12-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_assistance_death_cert_alter_membership_beneficiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_first_name', models.CharField(help_text='The first name of the dependent', max_length=50)),
                ('dependent_middle_name', models.CharField(blank=True, help_text='The middle name of the dependent', max_length=50, null=True)),
                ('dependent_last_name', models.CharField(help_text='The last name of the dependent', max_length=100)),
                ('suffix', models.CharField(blank=True, help_text='The suffix of the dependent', max_length=10, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='The gender of the dependent', max_length=10)),
                ('relationship_to_member', models.CharField(choices=[('Daugther', 'Daugther'), ('Son', 'Son')], help_text='The relationship to the member', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='The date added to the relationship')),
            ],
        ),
        migrations.AlterField(
            model_name='assistance',
            name='assistance_evidence_first',
            field=models.ImageField(blank=True, help_text='Upload medical certification', null=True, upload_to='assistance/proof/'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='assistance_evidence_second',
            field=models.ImageField(blank=True, help_text='Upload hospital certificate', null=True, upload_to='assistance/proof/'),
        ),
    ]
