# Generated by Django 5.1.1 on 2024-09-29 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_assistance_suffix_alter_beneficiary_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='date_released',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
