# Generated by Django 5.1.1 on 2024-12-01 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_dependents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependents',
            name='related_to_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.membership'),
        ),
    ]
