# Generated by Django 5.1.1 on 2024-12-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_membership_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='contact_number',
            field=models.CharField(help_text='Contact number of the employee', max_length=11, unique=True),
        ),
    ]
