# Generated by Django 5.1.1 on 2024-12-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_membership_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistance',
            name='suffix',
        ),
    ]
