# Generated by Django 5.1.1 on 2024-12-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_dependents_related_to_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='my_dependents',
            field=models.ManyToManyField(blank=True, help_text='Select dependent of the employee, select multiple.', null=True, to='system.dependents'),
        ),
        migrations.AlterField(
            model_name='dependents',
            name='relationship_to_member',
            field=models.CharField(choices=[('Daughter', 'Daughter'), ('Son', 'Son')], help_text='The relationship to the member', max_length=50),
        ),
        migrations.AlterField(
            model_name='membership',
            name='school_affiliation',
            field=models.CharField(choices=[('Dapiawan CES', 'Dapiawan CES'), ('Datu Pendililang ES', 'Datu Pendililang ES'), ('Madia IS', 'Madia IS'), ('Elian ES', 'Elian ES'), ('Gawang ES', 'Gawang ES'), ('Kitango ES', 'Kitango ES'), ('Kitapok ES', 'Kitapok ES'), ('Datu Kogia ES', 'Datu Kogia ES'), ('Dimaukom Utto ES', 'Dimaukom Utto ES'), ('Dimaukom ES', 'Dimaukom ES')], help_text='School affiliation of the employee', max_length=100),
        ),
    ]
