# Generated by Django 5.1.1 on 2024-12-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_remove_assistance_suffix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistance',
            options={'ordering': ['-date_released'], 'verbose_name': 'Assistance', 'verbose_name_plural': 'Assistances'},
        ),
        migrations.AlterField(
            model_name='assistance',
            name='amount_released',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount applied in assistance', max_digits=10),
        ),
    ]
