# Generated by Django 5.1.1 on 2024-12-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_membership_my_dependents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnenrollReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unenrolled_member_name', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('date_unenrolled', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dependents',
            name='relationship_to_member',
            field=models.CharField(choices=[('Daughter', 'Daughter'), ('Son', 'Son'), ('Spouse', 'Spouse'), ('Father', 'Father'), ('Mother', 'Mother')], help_text='The relationship to the member', max_length=50),
        ),
        migrations.AlterField(
            model_name='membership',
            name='my_dependents',
            field=models.ManyToManyField(blank=True, help_text='Select dependent of the employee, select multiple.', to='system.dependents'),
        ),
    ]
