# Generated by Django 5.1.1 on 2024-12-06 09:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_assistance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='user_id',
            field=models.ForeignKey(help_text='Select related user to the beneficiary', limit_choices_to={'membership_status': True}, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_membership', to='system.membership'),
        ),
        migrations.AlterField(
            model_name='dependents',
            name='related_to_member',
            field=models.ForeignKey(blank=True, limit_choices_to={'membership_status': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.membership'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user_id',
            field=models.OneToOneField(help_text='Employee who want to be a member', limit_choices_to={'is_active': True, 'user_type': 'Employee'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_by',
            field=models.ForeignKey(help_text='Employee who paid', limit_choices_to={'membership_status': True, 'user_id__user_type': 'Employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_name', to='system.membership'),
        ),
    ]
